version: '3'
services:
  db:
    image: postgis/postgis
    environment:
      POSTGRES_DB: seating
      POSTGRES_PASSWORD: secret
  backend:
    depends_on: [db, frontend]
    build:
      context: backend
      dockerfile: Dockerfile.dev
    ports: ['8080:8080']
    environment:
      DB_URL: postgres://postgres:secret@db:5432/seating
    volumes:
      - ./backend:/usr/src/app
      - ./frontend/static:/usr/src/app/static
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile.dev
    ports: ['8081:8081']
    volumes:
      - ./frontend:/usr/src/app
