#!/bin/bash
set -e -o pipefail
cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1


function start { # [...frontend|backend|db]: builds & starts dev servers (detached)
  docker-compose up -d --build "$@" && logs "$@"
}

function logs { # [...frontend|backend|db]: tails logs of dev servers
  docker-compose logs -f "$@"
}

function stop { # [...frontend|backend|db]: stops dev servers
  docker-compose stop "$@"
}


if [[ $# -eq 0 || "$1" == "help" ]]; then
  sed -En 's/^function (.*) {( #)?/\1/p' "$0"
else
  "$@"
fi